spring.application.name=api-monitoring-starter

# API Monitoring Configuration
api.monitoring.enabled=true
api.monitoring.include-internal=false
api.monitoring.exclude-packages=org.springframework,org.springframework.boot,org.springframework.security

# Logging Configuration
spring.logback.config=logback-spring.xml

management.endpoints.web.exposure.include=health,info,metrics,env,loggers,mappings,threaddump

management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# Useful application information
management.info.java.enabled=true
management.info.os.enabled=true
management.info.process.enabled=true
management.info.env.enabled=true

# Optional
info.app.name=${spring.application.name}
info.app.description=Micro Learning API
info.app.version=1.0.0